stages:
  - stage_1
  - stage_2
  - stage_3

job_build:
  stage: stage_1
  tags:
    - devops-linux
  script:
    - echo "Do build here"

job_test_1:
  stage: stage_2
  tags:
    - devops-linux
  script:
    - echo "Do test here"

job_test_2:
  stage: stage_2
  tags:
    - devops-linux
  script:
    - echo "Do test here"

job_deploy:
  stage: stage_3
  tags:
    - devops-linux
  script:
    - echo "Do deploy here"
