stages:
  - stage_1
  - stage_2
  - stage_3

job_build:
  stage: stage_1
  tags:
    - devops-linux
  script:
    - echo "Do build here"

job_test_1:
  stage: stage_2
  tags:
    - devops-linux
  script:
    - echo "Do test here"

job_test_2:
  stage: stage_2
  tags:
    - devops-linux
  script:
    - echo "Do test here"

job_deploy:
  stage: stage_3
  tags:
    - devops-linux
  script:
    - echo "Do deploy here"

# trigger_job:
#   stage: bridge_push_downstream 
#   trigger:
#     project: devops/demo/downstream_projects/demo_downstream_projects_2
#     # branch: branch_with_fails_for_demo
#     strategy: depend

# trigger_job:
#   stage: bridge_push_downstream
#   trigger:
#     project: devops/demo/downstream_projects/demo_downstream_projects_2
#     branch: branch_with_fails_for_demo
#     strategy: depend

# trigger_job_1:
#   stage: bridge_push_downstream
#   trigger:
#     project: devops/demo/downstream_projects/demo_downstream_projects_1

# trigger_job_2:
#   stage: bridge_push_downstream
#   trigger:
#     project: devops/demo/downstream_projects/demo_downstream_projects_2

# stages:
#   - test
#   - stage_1
#   - stage_2
#   - stage_3
#   - bridge_for_push_downstream

# # upstream_bridge:
# #   stage: test
# #   needs:
# #     pipeline: devops/demo/upstream_projects/demo_upstream_projects_1

# rspec:
#   stage: test
#   tags:
#     - devops-linux
#   script: echo "test"

# # staging:
# #   variables:
# #     ENVIRONMENT: staging
# #   stage: deploy
# #   trigger: devops/demo/downstream_projects/demo_downstream_projects_1

# # upstream_bridge:
# #   stage: test
# #   needs:
# #     pipeline: devops/demo/upstream_projects/demo_upstream_projects_2/pipelines


# job_build:
#   stage: stage_1
#   tags:
#     - devops-linux
#   script:
#     - echo "Do your build here"

# job_test_1:
#   stage: stage_2
#   tags:
#     - devops-linux
#   script:
#     - echo "Do a test here"

# job_test_2:
#   stage: stage_2
#   tags:
#     - devops-linux
#   script:
#     - echo "Do a test here"

# job_deploy:
#   stage: stage_3
#   tags:
#     - devops-linux
#   script:
#     - echo "Do a deploy "

# trigger_job:
#   stage: bridge_for_push_downstream 
#   trigger:
#     project: devops/demo/downstream_projects/demo_downstream_projects_2
#     strategy: depend

# # bridge:
# #   stage: bridge_for_push_downstream
# #   trigger: devops/demo/downstream_projects/demo_downstream_projects_1

# # upstream_bridge:
# #   stage: monitor_upstream
# #   needs:
# #     pipeline: devops/demo/upstream_projects/demo_upstream_projects_1


# bridge_1:
#   variables:
#     MY_VAR_1: my-value-1-for-demo_downstream_projects_1
#   stage: bridge_for_push_downstream
#   trigger:
#     project: devops/demo/downstream_projects/demo_downstream_projects_1
#     # strategy: depend

# # bridge_1:
# #   variables:
# #     MY_VAR_1: my-value-1-for-demo_downstream_projects_1
# #   stage: bridge_for_push_downstream
# #   trigger:
# #     project: devops/demo/downstream_projects/demo_downstream_projects_1
# #     strategy: depend

# # bridge_2:
# #   variables:
# #     MY_VAR_1: my-value-1-for-demo_downstream_projects_2
# #   stage: bridge_for_push_downstream
# #   trigger: 
# #     project: devops/demo/downstream_projects/demo_downstream_projects_2
# #     branch: some_branch